<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContentListTable extends Doctrine_Table
{
  public function getContentQuery($q)
  {
    return $q->leftJoin('cr.ContentType crct');
  }
}