<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContentSlotType extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_slot_type');
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('ContentSlot as Slots', array('local' => 'id',
                                                     'foreign' => 'content_slot_type_id'));
    }
}