<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSite extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site');
        $this->hasColumn('layout', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('title', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('description', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $this->hasMany('MenuItem as MenuItems', array('local' => 'id',
                                                      'foreign' => 'site_id'));

        $this->hasMany('Content', array('local' => 'id',
                                        'foreign' => 'site_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'title')));
        $this->actAs($sluggable0);
    }
}