<?php

/**
 * BaseContentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $label
 * @property string $list_route_url
 * @property string $view_route_url
 * @property string $layout
 * @property Doctrine_Collection $MenuItems
 * @property Doctrine_Collection $Content
 * @property Doctrine_Collection $Templates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseContentType extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_type');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('label', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('list_route_url', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('view_route_url', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('layout', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('MenuItem as MenuItems', array('local' => 'id',
                                                      'foreign' => 'content_type_id'));

        $this->hasMany('Content', array('local' => 'id',
                                        'foreign' => 'content_type_id'));

        $this->hasMany('ContentTemplate as Templates', array('local' => 'id',
                                                             'foreign' => 'content_type_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'name')));
        $this->actAs($sluggable0);
    }
}