<?php

/**
 * BaseEntityPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entity_id
 * @property integer $permission_id
 * @property Entity $Entity
 * @property sfGuardPermission $Permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseEntityPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_permission');
        $this->hasColumn('entity_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
        $this->hasColumn('permission_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('Entity', array('local' => 'entity_id',
                                      'foreign' => 'id',
                                      'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as Permission', array('local' => 'permission_id',
                                                               'foreign' => 'id',
                                                               'onDelete' => 'CASCADE'));
    }
}