<?php

/**
 * BaseContentPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $permission_id
 * @property Content $Content
 * @property sfGuardPermission $Permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseContentPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_permission');
        $this->hasColumn('content_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
        $this->hasColumn('permission_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('Content', array('local' => 'content_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as Permission', array('local' => 'permission_id',
                                                               'foreign' => 'id',
                                                               'onDelete' => 'CASCADE'));
    }
}