<?php

/**
 * BaseContentTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property enum $type
 * @property integer $content_type_id
 * @property string $partial_path
 * @property string $component_path
 * @property clob $body
 * @property ContentType $ContentType
 * @property Doctrine_Collection $Content
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseContentTemplate extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_template');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('type', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'View', 1 => 'List')));
        $this->hasColumn('content_type_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('partial_path', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('component_path', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $this->hasOne('ContentType', array('local' => 'content_type_id',
                                           'foreign' => 'id'));

        $this->hasMany('Content', array('local' => 'id',
                                        'foreign' => 'content_template_id'));
    }
}