<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContentPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_permission');
        $this->hasColumn('content_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
        $this->hasColumn('permission_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
    }

    public function setUp()
    {
        $this->hasOne('Content', array('local' => 'content_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array('local' => 'permission_id',
                                          'foreign' => 'id',
                                          'onDelete' => 'CASCADE'));
    }
}