<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEntityType extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_type');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('label', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('list_route_url', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('view_route_url', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('layout', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('MenuItem as MenuItems', array('local' => 'id',
                                                      'foreign' => 'entity_type_id'));

        $this->hasMany('Entity as Entities', array('local' => 'id',
                                                   'foreign' => 'entity_type_id'));

        $this->hasMany('EntityTemplate as Templates', array('local' => 'id',
                                                            'foreign' => 'entity_type_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array('fields' => array(0 => 'name')));
        $this->actAs($sluggable0);
    }
}