<?php

/**
 * BaseContentSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $content_id
 * @property integer $content_slot_type_id
 * @property string $name
 * @property clob $value
 * @property Content $RelatedContent
 * @property ContentSlotType $Type
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseContentSlot extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_slot');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('content_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('content_slot_type_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('value', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $this->hasOne('Content as RelatedContent', array('local' => 'content_id',
                                                         'foreign' => 'id',
                                                         'onDelete' => 'CASCADE'));

        $this->hasOne('ContentSlotType as Type', array('local' => 'content_slot_type_id',
                                                       'foreign' => 'id',
                                                       'onDelete' => 'CASCADE'));

        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'value')));
        $this->actAs($i18n0);
    }
}