<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEntityTemplate extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_template');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('type', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'View', 1 => 'List')));
        $this->hasColumn('entity_type_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('partial_path', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('component_path', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $this->hasOne('EntityType', array('local' => 'entity_type_id',
                                          'foreign' => 'id'));

        $this->hasMany('Entity as Entities', array('local' => 'id',
                                                   'foreign' => 'entity_template_id'));
    }
}