<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseContentGroup extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content_group');
        $this->hasColumn('content_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
        $this->hasColumn('group_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
    }

    public function setUp()
    {
        $this->hasOne('Content', array('local' => 'content_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'CASCADE'));

        $this->hasOne('Group', array('local' => 'group_id',
                                     'foreign' => 'id',
                                     'onDelete' => 'CASCADE'));
    }
}