<?php

/**
 * sfSympalContentSlotRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    elf-ekb.ru
 * @subpackage model
 * @author     Cluster Studio <clusterstudio@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfSympalContentSlotRef extends PluginsfSympalContentSlotRef
{
}
