<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/03/05 13:48:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=sympal;host=localhost',
  'username' => 'root',
  'name' => 'doctrine',
)),);
