<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/03/05 13:48:47
sfConfig::add(array(
  'app_sympal_settings_disallow_php_in_content' => false,
  'app_sympal_settings_default_layout' => 'sympal',
  'app_sympal_settings_default_site' => 'Sympal',
  'app_sympal_settings_enable_result_caching' => false,
  'app_sympal_settings_enable_query_caching' => false,
  'app_sympal_settings_rows_per_page' => 10,
  'app_sympal_settings_enabled_plugins' => array (
  0 => 'sfSympalPlugin',
  1 => 'sfSympalCommentsPlugin',
  2 => 'sfSympalI18nPlugin',
  3 => 'sfSympalMenuPlugin',
  4 => 'sfSympalPagesPlugin',
  5 => 'sfSympalRegisterPlugin',
  6 => 'sfSympalSecurityPlugin',
),
  'app_sympal_settings_Comments' => array (
  'enabled' => true,
  'enable_recaptcha' => true,
  'recaptcha_public_key' => '6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX',
  'recaptcha_private_key' => '6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb',
  'requires_auth' => true,
),
  'app_sympal_settings_I18n' => array (
  'enabled' => true,
  'slots' => true,
  'menus' => true,
  'Page' => true,
),
  'app_sympal_settings_Page' => array (
  'enable_comments' => true,
),
));
