<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/03/05 13:48:47
return array(
'sympal_homepage' => new sfRoute('/', array (
  'module' => 'sympal_frontend',
  'action' => 'index',
), array (
), array (
)),
'sympal_change_language' => new sfRoute('/change_language', array (
  'module' => 'sympal_editor',
  'action' => 'change_language',
), array (
), array (
)),
'sympal_logout' => new sfRoute('/logout', array (
  'module' => 'sympal_auth',
  'action' => 'signout',
), array (
), array (
)),
'sympal_toggle_edit' => new sfRoute('/toggle_edit', array (
  'module' => 'sympal_editor',
  'action' => 'toggle_edit',
), array (
), array (
)),
'sympal_edit_entity_slot' => new sfDoctrineRoute('/edit_entity_slot/:id', array (
  'module' => 'sympal_editor',
  'action' => 'edit_slot',
), array (
), array (
  'model' => 'EntitySlot',
  'type' => 'object',
)),
'sympal_save_entity_slot' => new sfDoctrineRoute('/edit_entity_slot/:id/save', array (
  'module' => 'sympal_editor',
  'action' => 'save_slot',
), array (
  'id' => '\\d+',
  'sf_method' => 
  array (
    0 => 'POST',
  ),
), array (
  'model' => 'EntitySlot',
  'type' => 'object',
)),
'sympal_preview_entity_slot' => new sfDoctrineRoute('/preview_entity_slot/:id', array (
  'module' => 'sympal_editor',
  'action' => 'preview_slot',
), array (
  'id' => '\\d+',
  'sf_method' => 
  array (
    0 => 'POST',
  ),
), array (
  'model' => 'EntitySlot',
  'type' => 'object',
)),
'sympal_change_entity_slot_type' => new sfDoctrineRoute('/change_entity_slot_type/:id/:type', array (
  'module' => 'sympal_editor',
  'action' => 'change_entity_slot_type',
), array (
), array (
  'model' => 'EntitySlot',
  'type' => 'object',
)),
'sympal_save_editor_panel_position' => new sfRoute('/save_editor_panel_position', array (
  'module' => 'sympal_editor',
  'action' => 'save_panel_position',
), array (
), array (
)),
'sympal_lock_entity' => new sfDoctrineRoute('/lock_entity/:id', array (
  'module' => 'sympal_editor',
  'action' => 'lock_entity',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
)),
'sympal_unlock_entity' => new sfDoctrineRoute('/unlock_entity/:id', array (
  'module' => 'sympal_editor',
  'action' => 'unlock_entity',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
)),
'sympal_publish_entity' => new sfDoctrineRoute('/publish_entity/:id', array (
  'module' => 'sympal_editor',
  'action' => 'publish_entity',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
)),
'sympal_unpublish_entity' => new sfDoctrineRoute('/unpublish_entity/:id', array (
  'module' => 'sympal_editor',
  'action' => 'unpublish_entity',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
)),
'sympal_config' => new sfRoute('/admin/configuration', array (
  'module' => 'sympal_config',
  'action' => 'index',
), array (
), array (
)),
'sympal_config_save' => new sfRoute('/admin/configuration/save', array (
  'module' => 'sympal_config',
  'action' => 'save',
), array (
), array (
)),
'sympal_entity_slot_types' => new sfDoctrineRouteCollection(array (
  'model' => 'EntitySlotType',
  'module' => 'sympal_entity_slot_types',
  'prefix_path' => 'admin/entities/slot_types',
  'with_wildcard_routes' => true,
  'name' => 'sympal_entity_slot_types',
  'requirements' => 
  array (
  ),
)),
'sympal_entity_templates' => new sfDoctrineRouteCollection(array (
  'model' => 'EntityTemplate',
  'module' => 'sympal_entity_templates',
  'prefix_path' => 'admin/entities/templates',
  'with_wildcard_routes' => true,
  'name' => 'sympal_entity_templates',
  'requirements' => 
  array (
  ),
)),
'sympal_entity_types' => new sfDoctrineRouteCollection(array (
  'model' => 'EntityType',
  'module' => 'sympal_entity_types',
  'prefix_path' => 'admin/entities/types',
  'with_wildcard_routes' => true,
  'name' => 'sympal_entity_types',
  'requirements' => 
  array (
  ),
)),
'sympal_sites' => new sfDoctrineRouteCollection(array (
  'model' => 'Site',
  'module' => 'sympal_sites',
  'prefix_path' => 'admin/sites',
  'with_wildcard_routes' => true,
  'name' => 'sympal_sites',
  'requirements' => 
  array (
  ),
)),
'sympal_entities' => new sfDoctrineRouteCollection(array (
  'model' => 'Entity',
  'module' => 'sympal_entities',
  'prefix_path' => 'admin/entities',
  'with_wildcard_routes' => true,
  'column' => 'slug',
  'name' => 'sympal_entities',
  'requirements' => 
  array (
    'slug' => NULL,
  ),
)),
'sympal_entities_create_type' => new sfRoute('/admin/entities/create/:type', array (
  'module' => 'sympal_entities',
  'action' => 'create_type',
), array (
), array (
)),
'sympal_entity_1' => new sfDoctrineRoute('/', array (
  'module' => 'sympal_entity',
  'action' => 'view',
  'sf_format' => 'html',
  'entity_route' => true,
  'id' => 1,
  'slug' => 'home',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
  'method' => 'getEntity',
)),
'sympal_home' => new sfDoctrineRoute('/', array (
  'module' => 'sympal_entity',
  'action' => 'view',
  'sf_format' => 'html',
  'entity_route' => true,
  'id' => 1,
  'slug' => 'home',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
  'method' => 'getEntity',
)),
'sympal_entity_5' => new sfDoctrineRoute('/register.:sf_format', array (
  'module' => 'sympal_entity',
  'action' => 'view',
  'sf_format' => 'html',
  'entity_route' => true,
  'id' => 5,
  'slug' => 'register',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
  'method' => 'getEntity',
)),
'sympal_register' => new sfDoctrineRoute('/register.:sf_format', array (
  'module' => 'sympal_entity',
  'action' => 'view',
  'sf_format' => 'html',
  'entity_route' => true,
  'id' => 5,
  'slug' => 'register',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
  'method' => 'getEntity',
)),
'sympal_entity_type_1' => new sfDoctrineRoute('/pages.:sf_format', array (
  'module' => 'sympal_entity',
  'action' => 'index',
  'sf_format' => 'html',
  'type' => 'page',
), array (
), array (
  'model' => 'Entity',
  'type' => 'list',
  'method' => 'getEntitiesForSite',
)),
'sympal_entity_view_type_1' => new sfDoctrineRoute('/:slug.:sf_format', array (
  'module' => 'sympal_entity',
  'action' => 'view',
  'sf_format' => 'html',
), array (
), array (
  'model' => 'Entity',
  'type' => 'object',
  'method' => 'getEntityForSite',
)),
'sympal_create_comment' => new sfRoute('/create_comment', array (
  'module' => 'sympal_comments',
  'action' => 'create',
), array (
), array (
)),
'sympal_comments' => new sfDoctrineRouteCollection(array (
  'model' => 'Comment',
  'module' => 'sympal_comments',
  'prefix_path' => 'admin/comments',
  'with_wildcard_routes' => true,
  'name' => 'sympal_comments',
  'requirements' => 
  array (
  ),
)),
'sympal_languages' => new sfDoctrineRouteCollection(array (
  'model' => 'Language',
  'module' => 'sympal_languages',
  'prefix_path' => 'admin/i18n/languages',
  'with_wildcard_routes' => true,
  'name' => 'sympal_languages',
  'requirements' => 
  array (
  ),
)),
'sympal_translations' => new sfDoctrineRouteCollection(array (
  'model' => 'Translation',
  'module' => 'sympal_translations',
  'prefix_path' => 'admin/i18n/translations',
  'with_wildcard_routes' => true,
  'name' => 'sympal_translations',
  'requirements' => 
  array (
  ),
)),
'sympal_menu_items' => new sfDoctrineRouteCollection(array (
  'model' => 'MenuItem',
  'module' => 'sympal_menu_items',
  'prefix_path' => 'admin/menus',
  'with_wildcard_routes' => true,
  'name' => 'sympal_menu_items',
  'requirements' => 
  array (
  ),
)),
'sympal_register_save' => new sfRoute('/register/save', array (
  'module' => 'sympal_register',
  'action' => 'save',
), array (
), array (
)),
'sympal_login' => new sfRoute('/login', array (
  'module' => 'sympal_auth',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_users' => new sfDoctrineRouteCollection(array (
  'model' => 'sfGuardUser',
  'module' => 'sympal_users',
  'prefix_path' => 'admin/security/users',
  'with_wildcard_routes' => true,
  'name' => 'sf_guard_users',
  'requirements' => 
  array (
  ),
)),
'sf_guard_groups' => new sfDoctrineRouteCollection(array (
  'model' => 'sfGuardGroup',
  'module' => 'sympal_groups',
  'prefix_path' => 'admin/security/groups',
  'with_wildcard_routes' => true,
  'name' => 'sf_guard_groups',
  'requirements' => 
  array (
  ),
)),
'sf_guard_permissions' => new sfDoctrineRouteCollection(array (
  'model' => 'sfGuardPermission',
  'module' => 'sympal_permissions',
  'prefix_path' => 'admin/security/permissions',
  'with_wildcard_routes' => true,
  'name' => 'sf_guard_permissions',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'default',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
