<?php

/**
 * BaseUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property sfGuardUser $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseUserProfile extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_profile');
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('first_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('last_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('email_address', 'string', 255, array('type' => 'string', 'email' => true, 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as User', array('local' => 'user_id',
                                                   'foreign' => 'id',
                                                   'onDelete' => 'CASCADE'));

        $sfsympalentitytype0 = new sfSympalEntityType();
        $this->actAs($sfsympalentitytype0);
    }
}