<?php

/**
 * BasesfSympalMenuItemGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_item_id
 * @property integer $group_id
 * @property sfSympalMenuItem $MenuItem
 * @property sfGuardGroup $Group
 * 
 * @method integer               getMenuItemId()   Returns the current record's "menu_item_id" value
 * @method integer               getGroupId()      Returns the current record's "group_id" value
 * @method sfSympalMenuItem      getMenuItem()     Returns the current record's "MenuItem" value
 * @method sfGuardGroup          getGroup()        Returns the current record's "Group" value
 * @method sfSympalMenuItemGroup setMenuItemId()   Sets the current record's "menu_item_id" value
 * @method sfSympalMenuItemGroup setGroupId()      Sets the current record's "group_id" value
 * @method sfSympalMenuItemGroup setMenuItem()     Sets the current record's "MenuItem" value
 * @method sfSympalMenuItemGroup setGroup()        Sets the current record's "Group" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfSympalMenuItemGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_menu_item_group');
        $this->hasColumn('menu_item_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfSympalMenuItem as MenuItem', array(
             'local' => 'menu_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sfsympalrecordtemplate0 = new sfSympalRecordTemplate();
        $this->actAs($sfsympalrecordtemplate0);
    }
}