<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSympalContentTypeTable extends Doctrine_Table
{
  public function getAllContentTypes()
  {
    $q = $this->createQuery('t')
      ->orderBy('t.name ASC');

    $q->enableSympalResultCache('sympal_get_content_types');

    return $q->execute();
  }
}