<?php

/**
 * PluginEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEvent');
    }
}