<?php

/**
 * BasesfSympalContentAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $asset_id
 * @property sfSympalContent $Content
 * @property sfSympalAsset $Asset
 * 
 * @method integer              getContentId()  Returns the current record's "content_id" value
 * @method integer              getAssetId()    Returns the current record's "asset_id" value
 * @method sfSympalContent      getContent()    Returns the current record's "Content" value
 * @method sfSympalAsset        getAsset()      Returns the current record's "Asset" value
 * @method sfSympalContentAsset setContentId()  Sets the current record's "content_id" value
 * @method sfSympalContentAsset setAssetId()    Sets the current record's "asset_id" value
 * @method sfSympalContentAsset setContent()    Sets the current record's "Content" value
 * @method sfSympalContentAsset setAsset()      Sets the current record's "Asset" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfSympalContentAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_content_asset');
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfSympalContent as Content', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfSympalAsset as Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sfsympalrecordtemplate0 = new sfSympalRecordTemplate();
        $this->actAs($sfsympalrecordtemplate0);
    }
}