<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginRoute extends BaseRoute
{
  public function getRouteType()
  {
    return $this->type == 'View' ? 'object':'list';
  }

  public function getRouteName()
  {
    return str_replace('-', '_', $this['slug']);
  }

  public function getYaml()
  {
    if ($this->yaml_override)
    {
      return $this->yaml_override;
    } else {
      $yaml = array();
      $yaml[] = $this->getRouteName().':';

      if ($this->getUrl() != '/')
      {
        $yaml[] = '  url:  '.$this->getUrl().'.:sf_format';
      } else {
        $yaml[] = '  url:  '.$this->getUrl();
      }

      if ($contentId = $this->getContentId())
      {
        $yaml[] = '  param: { module: sympal_content_renderer, action: index, sf_format: html, result_type: '.$this->getRouteType().', sympal_content_type: '.$this->getContentType()->getName().', sympal_content_id: '.$contentId.' }';
      } else {
        $yaml[] = '  param: { module: sympal_content_renderer, action: index, sf_format: html, result_type: '.$this->getRouteType().', sympal_content_type: '.$this->getContentType()->getName().' }';
      }

      $yaml[] = '  class: sfDoctrineRoute';
      $yaml[] = '  options:';
      $yaml[] = '    model:  Content';
      $yaml[] = '    type:   '.$this->getRouteType();
      $yaml[] = '    method: '.($this->getTableMethod() ? $this->getTableMethod():'getContent');
      $yaml[] = '    requirements:';
      $yaml[] = '      sf_culture: ('.implode('|', sfSympalConfig::get('language_codes')).')';
      $yaml[] = '      sf_format:  ('.implode('|', sfSympalConfig::get('content_formats')).')';

      return implode("\n", $yaml);
    }
  }

  public function postSave($event)
  {
    @unlink(sfConfig::get('sf_cache_dir').'/'.sfConfig::get('sf_app').'/'.sfConfig::get('sf_environment').'/config/config_routing.yml.php');
  }
}