<?php

/**
 * PluginsfSympalRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginsfSympalRedirect extends BasesfSympalRedirect
{
  public function preSave($event)
  {
    parent::preSave($event);

    $this->source = $this->source[0] == '/' ? $this->source : '/'.$this->source;
  }
}