<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEntityTable extends Doctrine_Table
{
  public function getTypeQuery($params)
  {
    $request = sfContext::getInstance()->getRequest();

    if (isset($params['type']))
    {
      $q = Doctrine::getTable('EntityType')->createQuery('t')
        ->andWhere('t.slug = ?', $params['type']);
    } else if ($request->hasParameter('type')) {
      $q = Doctrine::getTable('EntityType')->createQuery('t')
        ->andWhere('t.slug = ?', $request->getParameter('type'));
    } else if (isset($params['slug'])) {
      $q = Doctrine_Query::create()
        ->select('t.*')
        ->from('EntityType t')
        ->leftJoin('t.Entities e')
        ->where('e.slug = ?', $params['slug']);
    }

    $type = $q->fetchOne();

    if ($type)
    {
      $q = Doctrine::getTable($type->getName())->getEntityQuery();
    } else {
      $q = $this->createQuery('e');
    }

    return $q;
  }

  public function getEntity($params)
  {
    $request = sfContext::getInstance()->getRequest();
    $id = $request->getParameter('id');
    $slug = $request->getParameter('slug');

    $q = $this->getTypeQuery(array('slug' => $slug))
      ->andWhere('e.slug = ?', $slug);

    return $this->fetchEntity($q);
  }

  public function getEntityForSite($params)
  {
    $q = $this->getTypeQuery($params)
      ->andWhere('e.slug = ?', $params['slug']);

    return $this->fetchEntity($q);
  }

  public function getEntitiesForSite($params)
  {
    $q = $this->getTypeQuery($params);
    $q->addOrderBy('e.date_published DESC');

    $pager = new sfDoctrinePager('Entity', sfSympalConfig::get('rows_per_page'));
    $pager->setQuery($q);

    return $pager;
  }

  public function fetchEntity($q)
  {
    $entity = $q->fetchOne();

    return $entity;
  }

  public function getBaseQuery()
  {
    $q = Doctrine_Query::create()
      ->from('Entity e')
      ->select('*')
      ->leftJoin('e.Slots sl')
      ->leftJoin('sl.Type sty')
      ->leftJoin('e.Type ty')
      ->leftJoin('ty.Templates t')
      ->leftJoin('e.MasterMenuItem m')
      ->leftJoin('e.MenuItem mm')
      ->leftJoin('m.Site si');

    if (!sfSympalConfig::isEditMode())
    {
      $q->andWhere('m.is_published = 1 OR mm.is_published = 1')
        ->andWhere('e.is_published = 1');
    }

    if (sfSympalConfig::isI18nEnabled('menus'))
    {
      $q->leftJoin('m.Translation mtr');
      $q->leftJoin('mm.Translation mmtr');
      $q->distinct('DISTINCT mmtr.lang');
    }

    if (sfSympalConfig::isI18nEnabled('slots'))
    {
      $q->leftJoin('sl.Translation sltr');
    }

    return $q;
  }
}