<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginVersionChange extends BaseVersionChange
{
  public function getRevertValue()
  {
    return (isset($this['old_value']) && $this['old_value']) ? $this['old_value']:$this['new_value'];
  }
}