<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginEntityType extends BaseEntityType
{
  public function __toString()
  {
    return (string) $this->getLabel();
  }

  public function setName($name)
  {
    $result = Doctrine_Query::create()
      ->from('EntityType t')
      ->where('t.name = ?', $name)
      ->fetchArray();

    if ($result)
    {
      $this->assignIdentifier($result[0]['id']);
      $this->hydrate($result[0]);
    } else {
      $this->_set('name', $name);
    }
  }

  public function getTemplate($type = 'View')
  {
    $templates = $this->getTemplates();
    if (isset($templates[$type]))
    {
      return $templates[$type];
    } else {
      foreach ($templates as $template)
      {
        if ($template->getType() == $type)
        {
          return $template;
        }
      }
    }
  }

  public function getSingularUpper()
  {
    return Doctrine::getTable($this->getName())->getOption('name');
  }

  public function getSingularLower()
  {
    return Doctrine_Inflector::tableize(Doctrine::getTable($this->getName())->getOption('name'));
  }

  public function getPluralUpper()
  {
    return Doctrine_Inflector::classify(Doctrine::getTable($this->getName())->getTableName()) . 's';
  }

  public function getPluralLower()
  {
    return Doctrine::getTable($this->getName())->getTableName() . 's';
  }

  public function getRoute($action = null)
  {
    return 'sympal_' . ($action ? $this->getPluralLower() . '_' . $action : $this->getPluralLower());
  }
}