<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSympalContentSlot extends BasesfSympalContentSlot
{
  protected
    $_contentRenderedFor,
    $_rendered;

  public function setContentRenderedFor(sfSympalContent $content)
  {
    $this->_contentRenderedFor = $content;
  }

  public function getContentRenderedFor()
  {
    return $this->_contentRenderedFor;
  }

  public function render()
  {
    if (!$this->_rendered)
    {
      if ($this->render_function)
      {
        $renderFunction = $this->render_function;
        if (method_exists($this->_contentRenderedFor, $renderFunction))
        {
          $this->_rendered = $this->_contentRenderedFor->$renderFunction($this);
        } else {
          sfSympalToolkit::autoloadHelper($renderFunction);
          $this->_rendered = $renderFunction($this->_contentRenderedFor, $this->name);
        }
      } else {
        $class = 'sfSympalContentSlot'.$this->Type->name.'Renderer';

        if (!class_exists($class))
        {
          $class = 'sfSympalContentSlotRenderer';
        }

        $renderer = new $class($this);
        $this->_rendered = (string) $renderer;
      }
    }
    return $this->_rendered;
  }

  public function setValue($value)
  {
    if ($this->is_column)
    {
      $name = $this->name;
      $this->_contentRenderedFor->$name = $value;
    }

    $this->_rendered = null;
    return $this->_set('value', $value);
  }

  public function getRawValue()
  {
    if ($this->is_column)
    {
      $name = $this->name;
      return $this->_contentRenderedFor->$name;
    } else {
      return $this->_get('value');
    }
  }

  public function hasValue()
  {
    return trim(strip_tags($this->render()));
  }
}