<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSympalContentType extends BasesfSympalContentType
{
  public function __toString()
  {
    return (string) $this->getLabel();
  }

  public function getTypeTemplate()
  {
    return $this->_get('Template');
  }

  public function getTemplate()
  {
    $template = $this->getTypeTemplate();
    if ($template && $template->exists())
    {
      return $template;
    }

    if ($this->hasReference('ContentTemplates'))
    {
      foreach ($this->ContentTemplates as $template)
      {
        if ($template->is_default)
        {
          return $template;
        }
      }

      foreach ($this->ContentTemplates as $template)
      {
        if (!$template->is_default && $template->content_type_id == $this->getId())
        {
          return $template;
        }
      }

      return $this->ContentTemplates->getFirst();
    }
  }

  public function getSingularUpper()
  {
    return Doctrine_Core::getTable($this->getName())->getOption('name');
  }

  public function getSingularLower()
  {
    return Doctrine_Inflector::tableize(Doctrine_Core::getTable($this->getName())->getOption('name'));
  }

  public function getPluralUpper()
  {
    return Doctrine_Inflector::classify(Doctrine_Core::getTable($this->getName())->getTableName()) . 's';
  }

  public function getPluralLower()
  {
    return Doctrine_Core::getTable($this->getName())->getTableName() . 's';
  }

  public function getRouteName()
  {
    return '@'.str_replace('-', '_', $this->getSlug());
  }

  public function getRoutePath()
  {
    $path = $this->default_path;
    if ($path != '/')
    {
      $path .= '.:sf_format';
    }
    return $path;
  }

  public function postInsert($event)
  {
    sfSympalContext::getInstance()->getSympalConfiguration()->getCache()->primeCache(true);
  }
}