<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEntityTable extends Doctrine_Table
{
  public function getTypeQuery($params)
  {
    $request = sfContext::getInstance()->getRequest();

    if (is_string($params))
    {
      $typeSlug = $params;
    } else if (is_array($params) && isset($params['type'])) {
      $typeSlug = $params['type'];
    } else if ($request->hasParameter('type')) {
      $typeSlug = $request->getParameter('type');
    }

    if (isset($typeSlug))
    {
      $q = Doctrine::getTable('EntityType')->createQuery('t')
        ->andWhere('t.slug = ? OR t.name = ?', array($typeSlug, $typeSlug));
    } else if (isset($params['slug'])) {
      $q = Doctrine_Query::create()
        ->select('t.*')
        ->from('EntityType t')
        ->leftJoin('t.Entities e')
        ->where('e.slug = ?', $params['slug']);
    }

    $type = $q->fetchOne();

    $table = Doctrine::getTable($type->getName());

    $defaultQuery = true;
    if ($type)
    {
      if (method_exists($table, 'getEntityQuery'))
      {
        $defaultQuery = false;
        $q = $table->getEntityQuery();
      }
    }

    if ($defaultQuery)
    {
      $q = $this->createQuery('e')
        ->innerJoin('e.'.$type['name']);

      if (sfConfig::get('sf_logging_enabled'))
      {
        sfContext::getInstance()->getLogger()->notice('To improve performance '.get_class($table).' should have a callable method named "getEntityQuery()" that efficiently selects all the required data for your entity type with joins and specific selects.');
      }
    }

    return $q;
  }

  public function getEntity($params)
  {
    $request = sfContext::getInstance()->getRequest();
    $id = $request->getParameter('id');
    $slug = $request->getParameter('slug');

    $q = $this->getTypeQuery(array('slug' => $slug))
      ->andWhere('e.slug = ?', $slug);

    return $this->fetchEntity($q);
  }

  public function getEntityForSite($params)
  {
    $q = $this->getTypeQuery($params)
      ->andWhere('e.slug = ?', $params['slug']);

    return $this->fetchEntity($q);
  }

  public function getEntitiesForSite($params)
  {
    $q = $this->getTypeQuery($params);
    $q->addOrderBy('e.date_published DESC');

    $pager = new sfDoctrinePager('Entity', sfSympalConfig::get('rows_per_page'));
    $pager->setQuery($q);

    return $pager;
  }

  public function fetchEntity($q)
  {
    $entity = $q->fetchOne();

    return $entity;
  }

  public function getBaseQuery()
  {
    $q = Doctrine_Query::create()
      ->from('Entity e')
      ->select('*')
      ->leftJoin('e.Slots sl')
      ->leftJoin('sl.Type sty')
      ->leftJoin('e.Type ty')
      ->leftJoin('ty.Templates t')
      ->leftJoin('e.MasterMenuItem m')
      ->leftJoin('e.MenuItem mm')
      ->leftJoin('m.Site si');

    if (!sfSympalTools::isEditMode())
    {
      $q->andWhere('m.is_published = 1 OR mm.is_published = 1')
        ->andWhere('e.is_published = 1');
    }

    if (sfSympalConfig::isI18nEnabled('menus'))
    {
      $q->leftJoin('m.Translation mtr');
      $q->leftJoin('mm.Translation mmtr');
      $q->distinct('DISTINCT mmtr.lang');
    }

    if (sfSympalConfig::isI18nEnabled('slots'))
    {
      $q->leftJoin('sl.Translation sltr');
    }

    return $q;
  }
}