<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSite extends BaseSite
{
  public function deleteSiteAndApplication()
  {
    $this->delete();
    $this->deleteApplication();
  }

  public function deleteApplication(Doctrine_Connection $conn = null)
  {
    sfToolkit::clearDirectory(sfConfig::get('sf_apps_dir').'/'.$this->slug);
    rmdir(sfConfig::get('sf_apps_dir').'/'.$this->slug);
    @unlink(sfConfig::get('sf_web_dir').'/'.$this->slug.'_dev.php');
    @unlink(sfConfig::get('sf_web_dir').'/'.$this->slug.'.php');
  }
}