<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSiteTable extends Doctrine_Table
{
  protected $_byIdentifierCache = array();

  public function findOneBySlug($slug)
  {
    if (!isset($this->_byIdentifierCache[$slug]))
    {
      $record = $this->findOneBy('slug', $slug);

      $this->_byIdentifierCache[$slug] = $record;
    }
    return $this->_byIdentifierCache[$slug];
  }
}