<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginContentTemplate extends BaseContentTemplate
{
  public function setName($name)
  {
    $result = Doctrine_Query::create()
      ->from('ContentTemplate t')
      ->where('t.name = ?', $name)
      ->fetchArray();

    if ($result)
    {
      $this->assignIdentifier($result[0]['id']);
      $this->hydrate($result[0]);
    } else {
      $this->_set('name', $name);
    }
  }
}