<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginRoute extends BaseRoute
{
  public function getRouteType()
  {
    return $this->type == 'View' ? 'object':'list';
  }

  public function getRouteName()
  {
    return str_replace('-', '_', $this['slug']);
  }

  public function postSave($event)
  {
    sfToolkit::clearGlob(sfConfig::get('sf_cache_dir'));
  }
}