<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginContentSlot extends BaseContentSlot
{
  public function render()
  {
    $class = 'sfSympalContentSlot'.$this->Type->name.'Renderer';
    if (!class_exists($class))
    {
      $class = 'sfSympalContentSlotRenderer';
    }
    $renderer = new $class($this);
    return (string) $renderer;
  }

  public function getValue()
  {
    return $this->getI18n('value');
  }

  public function setValue($value)
  {
    return $this->setI18n('value', $value);
  }
}