<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSympalContent extends BasesfSympalContent
{
  protected
    $_allPermissions,
    $_route,
    $_mainMenuItem;

  public static function createNew($type)
  {
    if (is_string($type))
    {
      $type = Doctrine_Core::getTable('sfSympalContentType')->findOneByName($type);

      if (!$type)
      {
        throw new InvalidArgumentException(sprintf('Could not find Sympal Content Type named "%s"', $type));
      }
    }

    if (!$type instanceof sfSympalContentType)
    {
      throw new InvalidArgumentException(sprintf('Invalid Content Type', $type));
    }

    $name = $type->name;

    $content = new sfSympalContent();
    $content->Type = $type;
    $content->$name = new $name();

    return $content;
  }

  public function hasSlot($name)
  {
    return isset($this->Slots[$name]) ? true : false;
  }

  public function hasSlots()
  {
    return count($this->Slots) > 0 ? true : false;
  }

  public function getSlot($name)
  {
    if ($this->hasSlot($name))
    {
      return $this->Slots[$name];
    }
    return null;
  }

  public function removeSlot(sfSympalContentSlot $slot)
  {
    return Doctrine_Core::getTable('sfSympalContentSlotRef')
      ->createQuery()
      ->delete()
      ->where('content_slot_id = ?', $slot->id)
      ->andWhere('content_id = ?', $this->id)
      ->execute();
  }

  public function addSlot(sfSympalContentSlot $slot)
  {
    $this->removeSlot($slot);

    $contentSlotRef = new sfSympalContentSlotRef();
    $contentSlotRef->content_slot_id = $slot->id;
    $contentSlotRef->content_id = $this->id;
    $contentSlotRef->save();

    return $contentSlotRef;
  }

  public function getOrCreateSlot($name, $type = 'Text', $isColumn = false, $renderFunction = null)
  {
    if (!$hasSlot = $this->hasSlot($name))
    {
      $slot = new sfSympalContentSlot();
      $slot->render_function = $renderFunction;
      if ($isColumn)
      {
        $slot->is_column = true;
      }

      if (!$slot->exists())
      {
        if ($isColumn)
        {
          $type = 'ContentProperty';
        }

        $slot->setName($name);
        $slot->setType($type);
        $slot->save();

        $this->addSlot($slot);
      }
    } else {
      $slot = $this->getSlot($name);
    }

    $slot->setContentRenderedFor($this);

    return $slot;
  }

  public function hasField($name)
  {
    $result = $this->_table->hasField($name);
    if (!$result)
    {
      $className = $this->getContentTypeClassName();
      $table = Doctrine_Core::getTable($className);
      if ($table->hasField($name))
      {
        $result = true;
      }
      if (sfSympalConfig::isI18nEnabled($className))
      {
        $table = Doctrine_Core::getTable($className.'Translation');
        if ($table->hasField($name))
        {
          $result = true;
        }
      }
    }
    return $result;
  }

  public function getUrl()
  {
    return $this->getRoute();
  }

  public function getPubDate()
  {
    return strtotime($this->date_published);
  }

  public function getContentTypeClassName()
  {
    $contentTypes = sfSympalContext::getInstance()->getSympalConfiguration()->getContentTypes();
    if (isset($contentTypes[$this['content_type_id']]))
    {
      return $contentTypes[$this['content_type_id']];
    } else {
      throw new sfException('Invalid content type id "'.$this['content_type_id'].'". Id was not found in content type cache.');
    }
  }

  public function getAllPermissions()
  {
    if (!$this->_allPermissions)
    {
      $this->_allPermissions = array();
      foreach ($this->Groups as $group)
      {
        foreach ($group->Permissions as $permission)
        {
          $this->_allPermissions[] = $permission->name;
        }
      }
    }
    return $this->_allPermissions;
  }

  public function __toString()
  {
    return $this->getHeaderTitle();
  }

  public function getTitle()
  {
    return $this->getHeaderTitle();
  }

  public function getRelatedMenuItem()
  {
    $menuItem = $this->_get('MenuItem');
    if ($menuItem && $menuItem->exists())
    {
      $this->_mainMenuItem = $menuItem;
    }
    return $this->_mainMenuItem;
  }

  public function getRecord()
  {
    if ($this['Type']['name'])
    {
      Doctrine_Core::initializeModels(array($this['Type']['name']));
      return $this[$this['Type']['name']];
    } else {
      return false;
    }
  }

  public function publish()
  {
    $this->date_published = new Doctrine_Expression('NOW()');
    $this->save();
    $this->refresh();
  }

  public function unpublish()
  {
    $this->date_published = null;
    $this->save();
  }

  public function getHeaderTitle()
  {
    if ($record = $this->getRecord())
    {
      $guesses = array('name',
                       'title',
                       'username',
                       'subject');

      // we try to guess a column which would give a good description of the object
      foreach ($guesses as $descriptionColumn)
      {
        try
        {
          return (string) $record->get($descriptionColumn);
        } catch (Exception $e) {}
      }
      return (string) $this;
    }

    return sprintf('No description for object of class "%s"', $this->getTable()->getComponentName());
  }

  public function getEditRoute()
  {
    if ($this->exists())
    {
      return '@sympal_content_edit?id='.$this['id'];
    } else {
      throw new sfException('You cannot get the edit route of a object that does not exist.');
    }
  }

  public function getFeedDescription()
  {
    return sfSympalContext::getInstance()
      ->getRenderer($this)
      ->render();
  }

  public function getAuthorName()
  {
    return $this->getCreatedBy()->getName();
  }

  public function getAuthorEmail()
  {
    return $this->getCreatedBy()->getEmailAddress();
  }

  public function getUniqueId()
  {
    return $this->getId().'-'.$this->getSlug();
  }

  public function getRouteName()
  {
    if ($this['custom_path'])
    {
      return '@sympal_content_' . str_replace('-', '_', $this['slug']);
    } else if ($this['Type']['default_path']) {
      return $this['Type']['route_name'];
    } else if ($this['slug']) {
      return '@sympal_content_view';
    }
  }

  public function getRoutePath()
  {
    if ($path = $this['custom_path'])
    {
      if ($path != '/')
      {
        $path .= '.:sf_format';
      }
      return $path;
    } else if ($path = $this['Type']['route_path']) {
      return $path;
    } else if ($this['slug']) {
      return '/content/:slug';
    }
  }

  public function getAutomaticUrlHierarchy()
  {
    $menuItem = $this->getMenuItem();
    unset($this->MenuItem);
    if ($menuItem)
    {
      $url = str_replace(' / ', '/', $menuItem->getBreadcrumbs($this)->getPathAsString());
      $e = explode('/', $url);
      unset($e[0]);
      $e = array_map(array('Doctrine_Inflector', 'urlize'), $e);
      $url = implode('/', $e);
      if ($url)
      {
        return '/'.$url;
      }
    }
  }

  public function getRoute($routeString = null, $path = null)
  {
    if (!$this->_route)
    {
      if (!$this->exists() || !$this['slug'])
      {
        return false;
      }

      if (method_exists($this->getContentTypeClassName(), 'getRoute'))
      {
        return $this->getRecord()->getRoute();
      }

      if (is_null($routeString))
      {
        $routeString = $this->getRouteName();
      }

      if (is_null($path))
      {
        $path = $this->getRoutePath();
      }

      $route = new sfRoute($path);
      $variables = $route->getVariables();

      $this->_route = $this->_fillRoute($routeString, $variables);
    }

    return $this->_route;
  }

  public function getEvaluatedRoutePath()
  {
    $route = url_for($this->getRoute());
    $replace = sfContext::getInstance()->getRequest()->getScriptName();

    return str_replace($replace, null, $route);
  }

  protected function _fillRoute($route, $variables)
  {
    $isI18nEnabled = sfSympalConfig::isI18nEnabled();

    $values = array();
    foreach (array_keys($variables) as $name)
    {
      if ($isI18nEnabled && $name == 'slug' && $this->hasField('i18n_slug') && $i18nSlug = $this->i18n_slug)
      {
        $values[$name] = $i18nSlug;
      } else if ($this->hasField($name)) {
        $values[$name] = $this->$name;
      } else if (method_exists($this, $method = 'get'.sfInflector::camelize($name))) {
        $values[$name] = $this->$method();
      }
    }

    if (!empty($values))
    {
      return $route.'?'.http_build_query($values);
    } else {
      return $route;
    }
  }

  public function loadMetaData(sfWebResponse $response)
  {
    // page title
    if ($pageTitle = $this['page_title'])
    {
      $response->setTitle($pageTitle);
    } else if ($pageTitle = $this['Site']['page_title']) {
      $response->setTitle($pageTitle);
    }

    // meta keywords
    if ($metaKeywords = $this['meta_keywords'])
    {
      $response->addMeta('keywords', $metaKeywords);
    } else if ($metaKeywords = $this['Site']['meta_keywords']) {
      $response->addMeta('keywords', $metaKeywords);
    }

    // meta description
    if ($metaDescription = $this['meta_description'])
    {
      $response->addMeta('description', $metaDescription);
    } else if ($metaDescription = $this['Site']['meta_description']) {
      $response->addMeta('description', $metaDescription);
    }
  }

  public function trySettingTitleProperty($value)
  {
    foreach (array('title', 'name', 'subject', 'header') as $name)
    {
      try {
        $this->$name = $value;
      } catch (Exception $e) {}
    }
  }

  public function addLink(sfSympalContent $content)
  {
    $link = new sfSympalContentLink();
    $link->content_id = $this->id;
    $link->linked_content_id = $content->id;
    $link->save();

    return $link;
  }

  public function addAsset(sfSympalAsset $asset)
  {
    $contentAsset = new sfSympalContentAsset();
    $contentAsset->content_id = $this->id;
    $contentAsset->asset_id = $asset->id;
    $contentAsset->save();

    return $contentAsset;
  }

  public function deleteLinkAndAssetReferences()
  {
    $this->deleteAssetReferences();
    $this->deleteLinkReferences();
  }

  public function deleteAssetReferences()
  {
    $count = Doctrine_Query::create()
      ->delete('sfSympalContentLink')
      ->where('content_id = ?', $this->getId())
      ->execute();
    return $count;
  }

  public function deleteLinkReferences()
  {
    $count = Doctrine_Query::create()
      ->delete('sfSympalContentAsset')
      ->where('content_id = ?', $this->getId())
      ->execute();
    return $count;
  }

  public function postInsert($event)
  {
    $event->getInvoker()->deleteLinkAndAssetReferences();
  }

  public function postUpdate($event)
  {
    $event->getInvoker()->deleteLinkAndAssetReferences();
  }

  public static function slugBuilder($text, $content)
  {
    if ($record = $content->getRecord())
    {
      try {
        return $record->slugBuilder($text);
      } catch (Doctrine_Record_UnknownPropertyException $e) {
        return Doctrine_Inflector::urlize($text);
      }
    } else {
      return Doctrine_Inflector::urlize($text);
    }
  }

  public function getTemplateToRenderWith()
  {
    if (!$template = $this->getTemplate())
    {
      $template = $this->getType()->getTemplate();
    }
    $template = $template ? $template : 'sympal_default/default_content_template';
    return $template;
  }

  public function getThemeToRenderWith()
  {
    if ($layout = $this->getTheme()) {
      return $layout;
    } else if ($layout = $this->getType()->getTheme()) {
      return $layout;
    } else if ($layout = $this->getSite()->getTheme()) {
      return $layout;
    } else {
      return sfSympalConfig::get('default_theme', null, $this->getSite()->getSlug());
    }
  }

  public function getSiteId()
  {
    return $this->_get('site_id');
  }

  public function getContentTypeId()
  {
    return $this->_get('content_type_id');
  }

  public function getLastUpdatedBy()
  {
    return $this->_get('LastUpdatedBy');
  }

  public function getLastUpdatedById()
  {
    return $this->_get('last_updated_by_id');
  }

  public function getCreatedBy()
  {
    return $this->_get('CreatedBy');
  }

  public function getCreatedById()
  {
    return $this->_get('created_by_id');
  }

  public function getDatePublished()
  {
    return $this->_get('date_published');
  }

  public function getCustomPath()
  {
    return $this->_get('custom_path');
  }

  public function getPageTitle()
  {
    return $this->_get('page_title');
  }

  public function getMetaKeywords()
  {
    return $this->_get('meta_keywords');
  }

  public function getMetaDescription()
  {
    return $this->_get('meta_description');
  }

  public function getI18nSlug()
  {
    return $this->_get('i18n_slug');
  }

  public function getSite()
  {
    return $this->_get('Site');
  }

  public function getType()
  {
    return $this->_get('Type');
  }

  public function getGroups()
  {
    return $this->_get('Groups');
  }

  public function getPermissions()
  {
    return $this->_get('Permissions');
  }

  public function getMenuItem()
  {
    return $this->_get('MenuItem');
  }

  public function getSlots()
  {
    return $this->_get('Slots');
  }

  public function getContentGroups()
  {
    return $this->_get('ContentGroups');
  }
}