<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginVersionChange extends BaseVersionChange
{
  public function getRevertValue()
  {
    return $this['old_value'];
  }
}