<?php

/**
 * PluginsfSympalRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginsfSympalRedirect extends BasesfSympalRedirect
{
  public function preSave($event)
  {
    parent::preSave($event);

    $this->source = $this->source[0] == '/' ? $this->source : '/'.$this->source;
  }

  public function getDestinationType()
  {
    if ($this->isDestinationUrl())
    {
      return 'url';
    }
    else if ($this->isDestinationRoute())
    {
      return 'route';
    }
    else if ($this->isDestinationPath())
    {
      return 'path';
    }
    else if ($this->isDestinationContent())
    {
      return 'content';
    }
  }

  public function getDestinationValue()
  {
    return $this->getDestinationType() == 'content' ? $this->content_id : $this->destination;
  }

  public function getDestinationText()
  {
    return sprintf('Redirecting to %s "%s"', $this->getDestinationType(), $this->getDestinationValue());
  }

  public function isDestinationUrl()
  {
    return substr($this->destination, 0, 3) ==='http' ? true : false;
  }

  public function isDestinationRoute()
  {
    return $this->destination && $this->destination[0] === '@' ? true : false;
  }

  public function isDestinationPath()
  {
    return isset($this->destination[0]) && $this->destination[0] === '/' ? true : false;
  }

  public function isDestinationContent()
  {
    return $this->content_id ? true : false;
  }
}