<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSympalContentTable extends sfSympalDoctrineTable
{
  public function getTypeQuery($typeName, $alias = 'c')
  {
    Doctrine_Core::initializeModels(array($typeName));
    return $this->createQuery($alias)
      ->innerJoin($alias.'.'.$typeName.' cr');
  }

  public function getFullTypeQuery($typeName, $alias = 'c')
  {
    $table = Doctrine_Core::getTable($typeName);

    $q = $this->getBaseQuery($alias);

    $q->innerJoin($alias.'.'.$typeName.' cr');

    if (sfSympalConfig::isI18nEnabled($typeName))
    {
      $q->leftJoin('cr.Translation crt');
    }

    if (method_exists($table, 'getContentQuery'))
    {
      $table->getContentQuery($q);
    }

    return $q;
  }

  public function getContent($params = array())
  {
    $request = sfContext::getInstance()->getRequest();
    $contentType = $request->getParameter('sympal_content_type');
    $contentId = $request->getParameter('sympal_content_id');
    $contentSlug = $request->getParameter('sympal_content_slug');
    $q = $this->getFullTypeQuery($contentType);

    if ($contentId)
    {
      $q->andWhere('c.id = ?', $contentId);
    } else if ($contentSlug) {
      if ($this->hasRelation('Translation') && $this->getRelation('Translation')->getTable()->hasField('slug'))
      {
        $q->andWhere('c.slug = ? OR ct.i18n_slug = ?', array($contentSlug, $contentSlug));
      } else {
        $q->andWhere('c.slug = ?', $contentSlug);
      }
    }

    foreach ($params as $key => $value)
    {
      if ($key == 'slug' && $this->hasRelation('Translation'))
      {
        $q->andWhere('c.slug = ? OR ct.i18n_slug = ?', array($value, $value));
        continue;
      }

      if ($this->hasField($key))
      {
        $q->andWhere('c.'.$key.' = ?', $value);
      } else if ($this->hasRelation('Translation') && $this->getRelation('Translation')->getTable()->hasField($key)) {
        $q->andWhere('ct.'.$key, $value);
      } else if ($this->getRelation($contentType)->getTable()->hasField($key)) {
        $q->andWhere('cr.'.$key.' = ?', $value);
      }
    }

    $content = $q->fetchOne();

    return $content;
  }

  public function getBaseQuery($alias = 'c')
  {
    $sympalContext = sfSympalContext::getInstance();
    $q = Doctrine_Query::create()
      ->from('sfSympalContent '.$alias)
      ->leftJoin($alias.'.Permissions p')
      ->leftJoin($alias.'.Groups g')
      ->leftJoin($alias.'.Template cte')
      ->leftJoin($alias.'.Slots sl INDEXBY sl.name')
      ->leftJoin('sl.Type sty')
      ->leftJoin($alias.'.Type ty')
      ->leftJoin('ty.Template tyt')
      ->leftJoin('ty.ContentTemplates t')
      ->leftJoin($alias.'.MasterMenuItem m')
      ->leftJoin($alias.'.MenuItem mm')
      ->leftJoin($alias.'.CreatedBy u')
      ->innerJoin($alias.'.Site csi')
      ->andWhere('csi.slug = ?', $sympalContext->getSiteSlug());

    $user = sfContext::getInstance()->getUser();

    if (!$user->isEditMode())
    {
      $expr = new Doctrine_Expression('NOW()');
      $q->andWhere($alias.'.is_published = ?', true)
        ->andWhere($alias.'.date_published <= '.$expr);
    }

    if (sfSympalConfig::isI18nEnabled('sfSympalContentSlot'))
    {
      $q->leftJoin('sl.Translation slt');
    }

    if (sfSympalConfig::isI18nEnabled('sfSympalContent'))
    {
      $q->leftJoin($alias.'.Translation ct');
    }

    if (sfSympalConfig::isI18nEnabled('sfSympalMenuItem'))
    {
      $q->leftJoin('m.Translation mt');
    }

    return $q;
  }

  public function getAdminGenQuery($q)
  {
    $q = Doctrine_Core::getTable('sfSympalContent')
      ->getFullTypeQuery(sfContext::getInstance()->getRequest()->getAttribute('content_type', 'sfSympalPage'), 'r');

    return $q;
  }
}