<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMenuItemGroup extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_item_group');
        $this->hasColumn('menu_item_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
        $this->hasColumn('group_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
    }

    public function setUp()
    {
        $this->hasOne('MenuItem', array('local' => 'menu_item_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $this->hasOne('Group', array('local' => 'group_id',
                                     'foreign' => 'id',
                                     'onDelete' => 'CASCADE'));
    }
}