<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMenuItemPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_item_permission');
        $this->hasColumn('menu_item_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
        $this->hasColumn('permission_id', 'integer', null, array('primary' => true, 'type' => 'integer'));
    }

    public function setUp()
    {
        $this->hasOne('MenuItem', array('local' => 'menu_item_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array('local' => 'permission_id',
                                          'foreign' => 'id',
                                          'onDelete' => 'CASCADE'));
    }
}