<?php

/**
 * BaseMenuItemPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_item_id
 * @property integer $permission_id
 * @property MenuItem $MenuItem
 * @property sfGuardPermission $Permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseMenuItemPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_item_permission');
        $this->hasColumn('menu_item_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
        $this->hasColumn('permission_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('MenuItem', array('local' => 'menu_item_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardPermission as Permission', array('local' => 'permission_id',
                                                               'foreign' => 'id',
                                                               'onDelete' => 'CASCADE'));
    }
}