<?php

/**
 * BaseMenuItemGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_item_id
 * @property integer $group_id
 * @property MenuItem $MenuItem
 * @property sfGuardGroup $Group
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseMenuItemGroup extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_item_group');
        $this->hasColumn('menu_item_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
        $this->hasColumn('group_id', 'integer', 4, array('primary' => true, 'type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('MenuItem', array('local' => 'menu_item_id',
                                        'foreign' => 'id',
                                        'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array('local' => 'group_id',
                                                     'foreign' => 'id',
                                                     'onDelete' => 'CASCADE'));
    }
}