<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSympalComment extends BasesfSympalComment
{
  public function getAuthorName()
  {
    if ($this->user_id)
    {
      return $this->getAuthor()->getName();
    } else {
      return ($this->name) ? $this->name : 'anonymous';
    }
  }
  
  /**
   * Returns the relevant email address for this comment - either from
   * the logged-in user or the actual email that was entered
   * 
   * @return string
   */
  public function getAuthorEmailAddress()
  {
    if ($this->user_id)
    {
      return $this->getAuthor()->getEmailAddress();
    } else {
      return $this->email_address;
    }
  }

  public function isApproved()
  {
    return $this->getStatus() == 'Approved' ? true : false;
  }
}