<?php

/**
 * BaseForgotPassword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $unique_key
 * @property timestamp $expires_at
 * @property sfGuardUser $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseForgotPassword extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forgot_password');
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('unique_key', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('expires_at', 'timestamp', null, array('type' => 'timestamp', 'notnull' => true));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as User', array('local' => 'user_id',
                                                   'foreign' => 'id',
                                                   'onDelete' => 'CASCADE'));
    }
}