<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUser extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('first_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('last_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('email_address', 'string', 255, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '255'));
        $this->hasColumn('username', 'string', 128, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '128'));
        $this->hasColumn('algorithm', 'string', 128, array('type' => 'string', 'default' => 'sha1', 'notnull' => true, 'length' => '128'));
        $this->hasColumn('salt', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('password', 'string', 128, array('type' => 'string', 'length' => '128'));
        $this->hasColumn('is_active', 'boolean', null, array('type' => 'boolean', 'default' => '1'));
        $this->hasColumn('is_super_admin', 'boolean', null, array('type' => 'boolean', 'default' => 0));
        $this->hasColumn('last_login', 'timestamp', null, array('type' => 'timestamp'));


        $this->index('is_active_idx', array('fields' => array(0 => 'is_active')));
    }

    public function setUp()
    {
        $this->hasMany('Group as groups', array('refClass' => 'UserGroup',
                                                'local' => 'user_id',
                                                'foreign' => 'group_id'));

        $this->hasMany('Permission as permissions', array('refClass' => 'UserPermission',
                                                          'local' => 'user_id',
                                                          'foreign' => 'permission_id'));

        $this->hasMany('Comment as Comments', array('local' => 'id',
                                                    'foreign' => 'user_id'));

        $this->hasMany('Content as LastUpdatedContent', array('local' => 'id',
                                                              'foreign' => 'last_updated_by'));

        $this->hasMany('Content as CreatedContent', array('local' => 'id',
                                                          'foreign' => 'created_by'));

        $this->hasMany('Content as LockedContent', array('local' => 'id',
                                                         'foreign' => 'locked_by'));

        $this->hasMany('UserPermission', array('local' => 'id',
                                               'foreign' => 'user_id'));

        $this->hasMany('UserGroup', array('local' => 'id',
                                          'foreign' => 'user_id'));

        $this->hasOne('RememberKey as RememberKeys', array('local' => 'id',
                                                           'foreign' => 'user_id'));

        $this->hasOne('ForgotPassword', array('local' => 'id',
                                              'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}