<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGroupPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_permission');
        $this->hasColumn('group_id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('permission_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    }

    public function setUp()
    {
        $this->hasOne('Group', array('local' => 'group_id',
                                     'foreign' => 'id',
                                     'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array('local' => 'permission_id',
                                          'foreign' => 'id',
                                          'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}