<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserPermission extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_permission');
        $this->hasColumn('user_id', 'integer', null, array('type' => 'integer', 'primary' => true));
        $this->hasColumn('permission_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    }

    public function setUp()
    {
        $this->hasOne('User', array('local' => 'user_id',
                                    'foreign' => 'id',
                                    'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array('local' => 'permission_id',
                                          'foreign' => 'id',
                                          'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}