<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRememberKey extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('remember_key');
        $this->hasColumn('user_id', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('remember_key', 'string', 32, array('type' => 'string', 'length' => '32'));
        $this->hasColumn('ip_address', 'string', 50, array('type' => 'string', 'primary' => true, 'length' => '50'));
    }

    public function setUp()
    {
        $this->hasOne('User', array('local' => 'user_id',
                                    'foreign' => 'id',
                                    'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}