<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGroup extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groups');
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'unique' => true, 'length' => '255'));
        $this->hasColumn('description', 'string', 1000, array('type' => 'string', 'length' => '1000'));
    }

    public function setUp()
    {
        $this->hasMany('User as Users', array('refClass' => 'UserGroup',
                                              'local' => 'group_id',
                                              'foreign' => 'user_id'));

        $this->hasMany('Permission as Permissions', array('refClass' => 'GroupPermission',
                                                          'local' => 'group_id',
                                                          'foreign' => 'permission_id'));

        $this->hasMany('MenuItem as MenuItems', array('refClass' => 'MenuItemGroup',
                                                      'local' => 'group_id',
                                                      'foreign' => 'menu_item_id'));

        $this->hasMany('MenuItemGroup as MenuItemGroups', array('local' => 'id',
                                                                'foreign' => 'group_id'));

        $this->hasMany('Content', array('refClass' => 'ContentGroup',
                                        'local' => 'group_id',
                                        'foreign' => 'content_id'));

        $this->hasMany('ContentGroup as ContentGroups', array('local' => 'id',
                                                              'foreign' => 'group_id'));

        $this->hasMany('GroupPermission', array('local' => 'id',
                                                'foreign' => 'group_id'));

        $this->hasMany('UserGroup', array('local' => 'id',
                                          'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}