<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCommentTable extends Doctrine_Table
{
  public function getNumPending()
  {
    return $this->createQuery('c')
      ->where('c.status = ?', 'Pending')
      ->count();
  }
}