<?php

/**
 * sfSympalSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
class sfSympalSite extends PluginsfSympalSite
{
}
