<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTranslation extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('translation');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'unique' => true, 'length' => '255'));
        $this->hasColumn('value', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $i18n0 = new Doctrine_Template_I18n(array('fields' => array(0 => 'value')));
        $this->actAs($i18n0);
    }
}