<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLanguage extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('code', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    }

}