<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEvent extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $sfsympalcontenttype0 = new sfSympalContentType();
        $this->actAs($sfsympalcontenttype0);
    }
}