<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUserProfile extends BaseUserProfile
{
  public function __toString()
  {
    return (string) $this->getName();
  }

  public function getName()
  {
    return trim($this->getFirstName().' '.$this->getLastName());
  }

  public function getGravatarUrl($size = 40)
  {
    $default = "http://www.somewhere.com/homestar.jpg";

    $url = 'http://www.gravatar.com/avatar.php?gravatar_id='.md5(strtolower($this->email_address)).'&default='.urlencode($default).'&size='.$size;
    return $url;
  }
}