<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePageComment extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page_comment');
        $this->hasColumn('page_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
        $this->hasColumn('comment_id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('Page', array('local' => 'page_id',
                                    'foreign' => 'id',
                                    'onDelete' => 'CASCADE'));

        $this->hasOne('Comment', array('local' => 'comment_id',
                                       'foreign' => 'id',
                                       'onDelete' => 'CASCADE'));
    }
}