<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlogPost extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post');
        $this->hasColumn('title', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('teaser', 'clob', null, array('type' => 'clob'));
    }

    public function setUp()
    {
        $sfsympalcontenttype0 = new sfSympalContentType();
        $this->actAs($sfsympalcontenttype0);
    }
}