<?php

/**
 * BasesfSympalContentComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $comment_id
 * @property sfSympalContent $Content
 * @property sfSympalComment $Comment
 * 
 * @method integer                getContentId()  Returns the current record's "content_id" value
 * @method integer                getCommentId()  Returns the current record's "comment_id" value
 * @method sfSympalContent        getContent()    Returns the current record's "Content" value
 * @method sfSympalComment        getComment()    Returns the current record's "Comment" value
 * @method sfSympalContentComment setContentId()  Sets the current record's "content_id" value
 * @method sfSympalContentComment setCommentId()  Sets the current record's "comment_id" value
 * @method sfSympalContentComment setContent()    Sets the current record's "Content" value
 * @method sfSympalContentComment setComment()    Sets the current record's "Comment" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfSympalContentComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_content_comment');
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfSympalContent as Content', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfSympalComment as Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}