<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageTable extends Doctrine_Table
{
  public function getEntityQuery()
  {
    $q = Doctrine::getTable('Entity')->getBaseQuery()
      ->innerJoin('e.Page p');

    if (sfSympalConfig::get('Comments', 'enabled') && sfSympalConfig::get('Page', 'enable_comments'))
    {
      $q->leftJoin('p.Comments c');
    }

    return $q;
  }
}