<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageTable extends Doctrine_Table
{
  public function getContentQuery()
  {
    $q = Doctrine::getTable('Content')->getBaseQuery()
      ->innerJoin('e.Page p');

    return $q;
  }
}