<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasesfGuardRememberKey extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_remember_key');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('remember_key', 'string', 32, array('type' => 'string', 'length' => '32'));
        $this->hasColumn('ip_address', 'string', 50, array('type' => 'string', 'primary' => true, 'length' => '50'));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser', array('local' => 'user_id',
                                           'foreign' => 'id',
                                           'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}