<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $status
 * @property integer $user_id
 * @property string $name
 * @property string $subject
 * @property clob $body
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $Content
 * @property Doctrine_Collection $ContentComments
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseComment extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('status', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'Pending', 1 => 'Approved', 2 => 'Denied'), 'default' => 'Pending', 'notnull' => true));
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('subject', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob', 'notnull' => true));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as Author', array('local' => 'user_id',
                                                     'foreign' => 'id',
                                                     'onDelete' => 'CASCADE'));

        $this->hasMany('Content', array('refClass' => 'ContentComment',
                                        'local' => 'comment_id',
                                        'foreign' => 'content_id'));

        $this->hasMany('ContentComment as ContentComments', array('local' => 'id',
                                                                  'foreign' => 'comment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}