<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseComment extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('status', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'Pending', 1 => 'Approved', 2 => 'Denied'), 'default' => 'Pending', 'notnull' => true));
        $this->hasColumn('user_id', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('subject', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob', 'notnull' => true));
    }

    public function setUp()
    {
        $this->hasOne('User as Author', array('local' => 'user_id',
                                              'foreign' => 'id',
                                              'onDelete' => 'CASCADE'));

        $this->hasMany('Content', array('refClass' => 'ContentComment',
                                        'local' => 'comment_id',
                                        'foreign' => 'content_id'));

        $this->hasMany('ContentComment as ContentComments', array('local' => 'id',
                                                                  'foreign' => 'comment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}