<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseComment extends sfSympalDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('status', 'enum', null, array('type' => 'enum', 'values' => array(0 => 'Pending', 1 => 'Approved', 2 => 'Denied'), 'default' => 'Pending', 'notnull' => true));
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('subject', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('body', 'clob', null, array('type' => 'clob', 'notnull' => true));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as Author', array('local' => 'user_id',
                                                     'foreign' => 'id',
                                                     'onDelete' => 'CASCADE'));

        $this->hasMany('Page as Pages', array('refClass' => 'PageComment',
                                              'local' => 'comment_id',
                                              'foreign' => 'page_id'));

        $this->hasMany('PageComment as PageComments', array('local' => 'id',
                                                            'foreign' => 'comment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}