<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSympalMenuItemTable extends Doctrine_Table
{
  public function findFirstMenu()
  {
    return $this->createQuery('m')
      ->select('m.*')
      ->innerJoin('m.Site s WITH s.slug = ?', sfConfig::get('sf_app'))
      ->orderBy('m.root_id ASC')
      ->limit(1)
      ->fetchOne();
  }

  public function getPluginInstallMenu()
  {
    $menu = $this->createQuery('m')
      ->select('m.*')
      ->innerJoin('m.Site s WITH s.slug = ?', sfConfig::get('sf_app'))
      ->where('m.slug = ?', sfSympalConfig::get('default_install_content_type_menu', null, 'primary'))
      ->fetchOne();
    if (!$menu)
    {
      $menu = Doctrine_Core::getTable('sfSympalMenuItem')->findFirstMenu();
    }
    return $menu;
  }

  public function getMenuHierarchies()
  {
    return $this->getMenusQuery()->execute(array(), Doctrine_Core::HYDRATE_RECORD_HIERARCHY);
  }

  public function getMenusQuery()
  {
    $q = $this->createQuery()
      ->from('sfSympalMenuItem m INDEXBY m.id')
      ->addSelect('m.*')
      ->leftJoin('m.Groups g')
      ->addSelect('g.id, g.name')
      ->leftJoin('g.Permissions gp')
      ->addSelect('gp.id, gp.name')
      ->leftJoin('m.RelatedContent c')
      ->addSelect('c.id, c.custom_path, c.slug, c.date_published')
      ->leftJoin('c.Type ct')
      ->addSelect('ct.id, ct.name, ct.default_path, ct.slug')
      ->innerJoin('m.Site s WITH s.slug = ?', sfConfig::get('sf_app'))
      ->orderBy('m.root_id, m.lft ASC');

    if (sfSympalConfig::isI18nEnabled('sfSympalContent'))
    {
      $q->leftJoin('c.Translation ctr');
      $q->addSelect('ctr.*');
    }

    if (sfSympalConfig::isI18nEnabled('sfSympalMenuItem'))
    {
      $q->leftJoin('m.Translation t');
      $q->addSelect('t.*');
    }

    return $q;
  }
}