<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMenuItemTable extends Doctrine_Table
{
  public function getForEntityType($type)
  {
    $q = Doctrine_Query::create()
      ->from('MenuItem m')
      ->leftJoin('m.EntityType t')
      ->andWhere('t.slug = ?', $type)
      ->andWhere('m.has_many_entities = 1')
      ->limit(1);

    if (!sfSympalTools::isEditMode())
    {
      $q->andWhere('m.is_published = 1');
    }

    return $q->fetchOne();
  }
}