<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSympalMenuItemTable extends sfSympalDoctrineTable
{
  public function getForContentType($contentType)
  {
    $q = Doctrine_Query::create()
      ->from('sfSympalMenuItem m')
      ->leftJoin('m.ContentType t')
      ->andWhere('t.name = ? OR t.slug = ?', array($contentType, $contentType))
      ->limit(1);

    $user = sfContext::getInstance()->getUser();
    if (!$user->isEditMode())
    {
      $q->andWhere('m.is_published = 1');
    }

    return $q->fetchOne();
  }

  public function getForSlug($slug)
  {
    $q = Doctrine_Query::create()
      ->from('sfSympalMenuItem m')
      ->leftJoin('m.ContentType t')
      ->where('m.slug = ?', $slug);
    return $q->fetchOne();
  }
}