<?php

/**
 * PluginsfSympalPlugin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginsfSympalPlugin extends BasesfSympalPlugin
{
  public function getRoute()
  {
    return '@sympal_plugin_manager_view?plugin='.$this->getName();
  }

  public function getActionRoute($action)
  {
    return '@sympal_plugin_manager_'.$action.'?plugin='.$this->getName();
  }

  public function getAuthorName()
  {
    return $this->getAuthor()->getName();
  }

  public function getAuthorEmail()
  {
    return $this->getAuthor()->getEmail();
  }

  public function isDownloaded()
  {
    return $this->getIsDownloaded();
  }

  public function isInstalled()
  {
    return $this->getIsInstalled();
  }

  public function getImage()
  {
    if (!$image = $this->_get('image'))
    {
      return 'http://www.symfony-project.org/images/plugin_default.png';
    } else {
      return $image;
    }
  }
}