<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPluginAuthor extends BasePluginAuthor
{
  public function setEmail($email)
  {
    if ($email)
    {
      $result = Doctrine_Query::create()
        ->from('PluginAuthor a')
        ->where('a.email = ?', $email)
        ->fetchArray();

      if ($result)
      {
        $this->assignIdentifier($result[0]['id']);
        $this->hydrate($result[0]);
      } else {
        $this->_set('email', $email);
      }
    }
  }
}