<?php

/**
 * BasesfSympalContentSlotRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_slot_id
 * @property integer $content_id
 * @property sfSympalContentSlot $Slot
 * @property sfSympalContent $Content
 * 
 * @method integer                getContentSlotId()   Returns the current record's "content_slot_id" value
 * @method integer                getContentId()       Returns the current record's "content_id" value
 * @method sfSympalContentSlot    getSlot()            Returns the current record's "Slot" value
 * @method sfSympalContent        getContent()         Returns the current record's "Content" value
 * @method sfSympalContentSlotRef setContentSlotId()   Sets the current record's "content_slot_id" value
 * @method sfSympalContentSlotRef setContentId()       Sets the current record's "content_id" value
 * @method sfSympalContentSlotRef setSlot()            Sets the current record's "Slot" value
 * @method sfSympalContentSlotRef setContent()         Sets the current record's "Content" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfSympalContentSlotRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_content_slot_ref');
        $this->hasColumn('content_slot_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfSympalContentSlot as Slot', array(
             'local' => 'content_slot_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfSympalContent as Content', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sfsympalrecordtemplate0 = new sfSympalRecordTemplate();
        $this->actAs($sfsympalrecordtemplate0);
    }
}