<?php

/**
 * BasesfSympalContentLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property integer $linked_content_id
 * @property sfSympalContent $Content
 * @property sfSympalContent $LinkedContent
 * 
 * @method integer             getContentId()         Returns the current record's "content_id" value
 * @method integer             getLinkedContentId()   Returns the current record's "linked_content_id" value
 * @method sfSympalContent     getContent()           Returns the current record's "Content" value
 * @method sfSympalContent     getLinkedContent()     Returns the current record's "LinkedContent" value
 * @method sfSympalContentLink setContentId()         Sets the current record's "content_id" value
 * @method sfSympalContentLink setLinkedContentId()   Sets the current record's "linked_content_id" value
 * @method sfSympalContentLink setContent()           Sets the current record's "Content" value
 * @method sfSympalContentLink setLinkedContent()     Sets the current record's "LinkedContent" value
 * 
 * @package    sympal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class BasesfSympalContentLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_sympal_content_link');
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('linked_content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfSympalContent as Content', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfSympalContent as LinkedContent', array(
             'local' => 'linked_content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sfsympalrecordtemplate0 = new sfSympalRecordTemplate();
        $this->actAs($sfsympalrecordtemplate0);
    }
}